# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20171016_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appgroups',
            name='app_path',
        ),
    ]
