# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_remove_appgroups_app_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerYamlConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaml_data', models.TextField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.AppGroups')),
            ],
            options={
                'verbose_name_plural': 'YAML配置表',
            },
        ),
    ]
