# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_dockeryamlconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': '任务-应用信息表',
            },
        ),
        migrations.CreateModel(
            name='MissionAppInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('status', models.SmallIntegerField(default=0, verbose_name='任务状态')),
            ],
            options={
                'verbose_name_plural': '任务-应用实例表',
            },
        ),
        migrations.CreateModel(
            name='MissionProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('app', models.ManyToManyField(related_name='mission_projects', to='repository.MissionApp')),
            ],
            options={
                'verbose_name_plural': '任务-项目信息表',
            },
        ),
        migrations.RemoveField(
            model_name='mission',
            name='app_id',
        ),
        migrations.AddField(
            model_name='missionapp',
            name='ip',
            field=models.ManyToManyField(related_name='mission_apps', to='repository.MissionAppInstance'),
        ),
        migrations.AddField(
            model_name='mission',
            name='project',
            field=models.ManyToManyField(to='repository.MissionProject'),
        ),
    ]
