# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20171019_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionapp',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='missionproject',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
