# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20171019_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionapp',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='project',
            field=models.ManyToManyField(related_name='missions', to='repository.MissionProject'),
        ),
    ]
