# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sn',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='SN号'),
            preserve_default=False,
        ),
    ]
