# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180220_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cpu_physical_count',
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_core_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU物理个数'),
        ),
    ]
