# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180220_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='latest_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
