# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=35, verbose_name='访问用户')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('routing', models.CharField(blank=True, max_length=200, verbose_name='访问地址')),
                ('ip_address', models.GenericIPAddressField(verbose_name='源地址')),
                ('cookies', models.CharField(blank=True, max_length=300, verbose_name='cookies值')),
                ('browser', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='浏览器信息')),
                ('system', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='客户端系统信息')),
            ],
            options={
                'ordering': ['-create_at'],
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=32)),
                ('url_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='url请求方法')),
                ('memo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '权限配置管理',
            },
        ),
    ]
