# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0003_auto_20180227_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('memo', models.CharField(blank=True, max_length=50, null=True)),
                ('permissions', models.ManyToManyField(related_name='roles_permission', to='user_center.Permission')),
            ],
            options={
                'verbose_name_plural': '角色配置管理',
            },
        ),
    ]
