# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0004_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(related_name='user_roles', to='user_center.Roles'),
        ),
    ]
