# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0005_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(max_length=150),
        ),
    ]
